# Generated by Django 5.1.7 on 2025-03-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.CharField(max_length=50)),
                ('cow_id', models.CharField(max_length=50, unique=True)),
                ('cow_name', models.CharField(max_length=100)),
                ('cow_color', models.CharField(max_length=50)),
                ('breeding_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
