# Generated by Django 5.1.7 on 2025-03-22 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_cowentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litres', models.FloatField()),
                ('price_per_litre', models.FloatField()),
                ('fat', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.login')),
            ],
        ),
    ]
