# Generated by Django 5.1.7 on 2025-03-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_milkentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkentry',
            name='total_amount',
            field=models.FloatField(editable=False),
        ),
    ]
