# Generated by Django 5.1.7 on 2025-03-22 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_delete_milkentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('litre', models.FloatField()),
                ('price_per_litre', models.FloatField()),
                ('fat', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.login', to_field='farmer_id')),
            ],
        ),
    ]
