# Generated by Django 5.1.7 on 2025-03-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_milkentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkentry',
            name='farmer_id',
            field=models.CharField(max_length=10),
        ),
    ]
